export const RECEIVING_YARDS_MULTIPLIER: number = 0.0075;
export const RECEIVING_YARDS_THRESHOLD_BEFORE_1980: number = 3500;
export const RECEIVING_YARDS_THRESHOLD_DURING_OR_AFTER_1980: number = 7500;
export const RECEIVING_TOUCHDOWNS_MULTIPLIER: number = 0.075;
export const RECEIVING_TOUCHDOWNS_THRESHOLD_BEFORE_1980: number = 35;
export const RECEIVING_TOUCHDOWNS_THRESHOLD_DURING_OR_AFTER_1980: number = 50;