export const RECEIVING_YARDS_MULTIPLIER: number = 0.0075;
export const RECEIVING_YARDS_THRESHOLD_BEFORE_1980: number = 7000;
export const RECEIVING_YARDS_THRESHOLD_DURING_OR_AFTER_1980: number = 10000;
export const RECEIVING_TOUCHDOWNS_MULTIPLIER: number = 0.075;
export const RECEIVING_TOUCHDOWNS_THRESHOLD_BEFORE_1980: number = 50;
export const RECEIVING_TOUCHDOWNS_THRESHOLD_DURING_OR_AFTER_1980: number = 65;
export const NO_CHAMPIONSHIPS_PENALTY: number = 2.5;