export const MONITOR_VALUES = {
    YEAR_1980: "1980",
    MOST_VALUABLE_PLAYER_MULTIPLIER: 12.5,
    DEFENSIVE_PLAYER_MULTIPLIER: 12.5,
    CHAMPIONSHIPS_WON_MULTIPLIER: 2,
    WEIGHTED_APPROXIMATE_VALUE_MULTIPLIER: 0.5,
    ALL_PRO_FIRST_TEAM_PERCENTAGE_BONUS: 25,
    HALL_OF_FAME_BALLOT_FINALIST_BONUS: 1,
    HALL_OF_FAME_BALLOT_SEMIFINALIST_BONUS: 0.5,
    EACH_YEAR_PLAYED_IN_AFL_PENALTY: 0.75,
    ALL_DECADE: {
        PRO_FOOTBALL_HALL_OF_FAME_ALL_DECADE_SELECTIONS_MULTIPLER: 25,
        FIRST_TEAM_OFFENSE_SELECTION: 1,
        FIRST_TEAM_DEFENSE_SELECTION: 1,
        FIRST_TEAM_SPECIAL_TEAMS_SELECTION: 0.5,
        SECOND_TEAM_OFFENSE_SELECTION: 0.4,
        SECOND_TEAM_DEFENSE_SELECTION: 0.4,
        SECOND_TEAM_SPECIAL_TEAMS_SELECTION: 0.5,
        OFFENSE_TEAMS_OTHER_SELECTION: 0.7,
        DEFENSE_TEAMS_OTHER_SELECTION: 0.7,
        SPECIAL_TEAMS_OTHER_SELECTION: 0.35,
    },
    QUARTERBACK: {
        CHAMPIONSHIPS_WON_MULTIPLIER: 2.5,
        SUPER_BOWL_LOSSES_MULTIPLIER: 1.25,
        PASSING_YARDS_MULTIPLIER: 0.0075,
        PASSING_YARDS_THRESHOLD_BEFORE_1980: 25000,
        PASSING_YARDS_THRESHOLD_DURING_OR_AFTER_1980: 40000,
        PASSING_TOUCHDOWNS_MULTIPLIER: 0.075,
        PASSING_TOUCHDOWNS_THRESHOLD_BEFORE_1980: 175,
        PASSING_TOUCHDOWNS_THRESHOLD_DURING_OR_AFTER_1980: 250,
        NO_CHAMPIONSHIPS_PENALTY: 7.5
    },
    RUNNING_BACK: {
        RUSHING_YARDS_MULTIPLIER: 0.0075,
        RUSHING_YARDS_THRESHOLD: 10000,
        RUSHING_TOUCHDOWNS_THRESHOLD: 70,
        NO_CHAMPIONSHIPS_PENALTY: 2.5
    },
    WIDE_RECEIVER: {
        RECEIVING_YARDS_MULTIPLIER: 0.0075,
        RECEIVING_YARDS_THRESHOLD_BEFORE_1980: 7000,
        RECEIVING_YARDS_THRESHOLD_DURING_OR_AFTER_1980: 10000,
        RECEIVING_TOUCHDOWNS_MULTIPLIER: 0.075,
        RECEIVING_TOUCHDOWNS_THRESHOLD_BEFORE_1980: 50,
        RECEIVING_TOUCHDOWNS_THRESHOLD_DURING_OR_AFTER_1980: 65,
        NO_CHAMPIONSHIPS_PENALTY: 2.5
    },
    TIGHT_END: {
        RECEIVING_YARDS_MULTIPLIER: 0.0075,
        RECEIVING_YARDS_THRESHOLD_BEFORE_1980: 3500,
        RECEIVING_YARDS_THRESHOLD_DURING_OR_AFTER_1980: 7500,
        RECEIVING_TOUCHDOWNS_MULTIPLIER: 0.075,
        RECEIVING_TOUCHDOWNS_THRESHOLD_BEFORE_1980: 35,
        RECEIVING_TOUCHDOWNS_THRESHOLD_DURING_OR_AFTER_1980: 50
    },
    OFFENSIVE_TACKLE_AND_GUARD: {
        NO_CHAMPIONSHIPS_PENALTY: 2.5
    },
    DEFENSIVE_END: {
        SACKS_MULTIPLIR: 0.25,
        NO_CHAMPIONSHIPS_PENALTY: 2.5
    },
    DEFENSIVE_TACKLE: {
        SACKS_MULTIPLIR: 0.25,
        NO_CHAMPIONSHIPS_PENALTY: 2.5
    },
    INSIDE_LINEBACKER: {
        INTERCEPTION_MULTIPLIR: 0.25,
        NO_CHAMPIONSHIPS_PENALTY: 5
    },
    OUTSIDE_LINEBACKER: {
        SACKS_MULTIPLIR: 0.25,
        NO_CHAMPIONSHIPS_PENALTY: 2.5
    },
    DEFENSIVE_BACK: {
        INTERCEPTION_MULTIPLIR: 0.25,
        NO_CHAMPIONSHIPS_PENALTY: 2.5
    },
    KICKERS: {
        FIELD_GOALS_MULTIPLIER: 0.25
    },
    PUNTERS: {
        NO_CHAMPIONSHIPS_PENALTY: 5
    }
}